version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/circleci-test
    
    steps:
      # git pull
      - checkout

      # setup testing env
      #- setup_remote_docker:
      #- run:
       #   name: Login to DockerHub
        #  command: docker login -u 'ppawave' -p 'Gnaopa199258$!'
      

      # Download and cache dependencies
      - restore_cache:
          keys:
          - sample-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: sample-{{ checksum "pom.xml" }}
        
      # package into a jar
      #- run: mvn clean package

      # build and push docker image to docker hub
      #- run: mvn clean compile com.google.cloud.tools:jib-maven-plugin:2.5.0:build -Dimage=ppawave/circleci-test:1.0.0

      - run:
          name: Build application Docker image
          command: |
              cp target/*.jar docker/apps/
                    docker login -u 'kophyo1992@icloud.com' -p 'Gnaopa199258$!' ppa-ppa-docker-local
                    docker build --no-cache -t ppa-ppa-docker-local/test/circleci-test:circleci-test docker
                    docker push ppa-ppa-docker-local/test/circleci-test:circleci-test

      # store raw contents of src code
      - store_artifacts:
          path: target/
          destination: sample
      - store_test_results:
          path: target/

